[build]
  command = "./build.sh"
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/gopycplus/viktorina-bot"
  GO111MODULE = "on"

[[redirects]]
  from = "/public/*"
  to = "/.netlify/functions/viktorina-bot-player/*"
  status = 200